### Register User
POST http://localhost:4000/api/user/register
Content-Type: application/json

{
    "firstName": "Mayank7",
    "lastName": "Agarwal7",
    "age": 30,
    "email": "mayankagofficial7@gmail.com",
    "password": "GoodPassword"
}

### Register 2nd User
POST http://localhost:4000/api/user/register
Content-Type: application/json

{
  "firstName": "Monika",
  "lastName": "Singh",
  "age": 50,
  "email": "monikasingh@gmail.com",
  "password": "GoodPassword@123"
}

### Register 3rd User
POST http://localhost:4000/api/user/register
Content-Type: application/json

{
  "firstName": "Sanu",
  "lastName": "Agarwal",
  "age": 18,
  "email": "sanuagarwal@gmail.com",
  "password": "GoodPassword@123456"
}