### Register User
POST http://localhost:8080/api/user/register
Content-Type: application/json

{
    "firstName": "Mayank",
    "lastName": "Agarwal",
    "age": 30,
    "email": "mayankagofficial@gmail.com",
    "password": "GoodPassword"
}

### Register 2nd User
POST http://localhost:8080/api/user/register
Content-Type: application/json

{
  "firstName": "Monika",
  "lastName": "Singh",
  "age": 50,
  "email": "monikasingh@gmail.com",
  "password": "GoodPassword@123"
}

### Login User
POST http://localhost:8080/api/user/login
Content-Type: application/json

{
    "email": "mayankagofficial@gmail.com",
    "password": "GoodPassword"
}

### Get All Users
GET http://localhost:8080/api/user/

### Register 3rd User
POST http://localhost:8080/api/user/register
Content-Type: application/json

{
  "firstName": "Sanu",
  "lastName": "Agarwal",
  "age": 10,
  "email": "sanuagarwal@gmail.com",
  "password": "GoodPassword@123456"
}